package org.krisbox.ihub.examples.utils.rest.endpoints;

/**
 * Created by kclark on 11/4/16.
 */
public abstract class RestConstants {
    public enum ENDPOINTS  {
        GET_DATAOBJECTS_DATAOBJECTID,
        GET_DATAOBJECTS_DATAOBJECTID_DATASETNAME,
        GET_FILES,
        GET_FILES_FILEID,
        GET_FILES_FILEID_DOWNLOAD,
        GET_FILES_FILEID_PRIVILEGES,
        GET_FILES_FILEID_SEARCH,
        GET_FILES_SEARCH,
        POST_FILES,
        POST_FILES_UPLOAD,
        PUT_FILES_FILEID,
        DELETE_FILES_FILEID,
        PATCH_FILES_FILEID,
        GET_JOBS,
        GET_JOBS_JOBID_STATUS,
        POST_JOBS_EXECUTE,
        POST_JOBS_SCHEDULE_NOW_REPORTID,
        POST_JOBS_SCHEDULE_ONCE_REPORTID,
        POST_JOBS_SCHEDULE_RECURRING_REPORTID,
        DELETE_JOBS_JOBID,
        POST_LOGIN,
        GET_USERGROUPS,
        GET_USERGROUPS_USERGROUPID,
        GET_USERGROUPS_USERGROUPID_USERS,
        PUT_USERGROUPS_USERGROUPID,
        POST_USERGROUPS,
        POST_USERGROUPS_USERGROUPID_USERS,
        POST_USERGROUPS_USERGROUPID_USERID,
        DELETE_USERGROUPS_USERGROUPID,
        DELETE_USERGROUPS_USERGROUPID_USERS,
        DELETE_USERGROUPS_USERGROUPID_USERS_USERID,
        PATCH_USERGROUPS_USERGROUPID,
        GET_USERS,
        GET_USERS_USERID,
        GET_USERS_USERID_USERGROUPS,
        POST_USERS,
        POST_USERS_USERID_USERGROUPS_USERGROUPID,
        POST_USERS_USERID_USERGROUPS,
        PUT_USERS_USERID,
        PATCH_USERS_USERID,
        DELETE_USERS_USERID,
        DELETE_USERS_USERID_USERGROUPS,
        DELETE_USERID_USERGROUPS_USERGROUPID,
        GET_VERSION,
        GET_VERSION_API,
        GET_VISUALS_VISUALID_BOOKMARKS,
        GET_VISUALS_VISUALID_BOOKMARKS_BOOKMARKNAME,
        GET_VISUALS_VISUALID_PARAMETERS,
        GET_VISUALS_VISUALID_PARAMETERS_PICKLIST,
        GET_VISUALS_VISUALID_PDF,
        GET_VISUALS_VISUALID_RESULTSETS,
        GET_VISUALS_VISUALID_RESULTSETS_RESULTSETNAME,
        GET_VISUALS_VISUALID_XLSX
    }

    public enum OUTPUT_TYPE {
        XLS, XLSX, DOC, DOCX, PPT, PPTX, PS, PDF, XHTML
    }
}
